### ISSUE TITLE
How did you do this?

### ISSUE THREAD

**Issue by dimitrieh** [mariuszostrowski/wireframingsketch#1]
Hey there, love it that you created this, however I am even more interested in how you created these! :)

**Comment by mariuszostrowski** [comment]
Hi, please select image and select from menu - Layer/Image/Convert to 9-Slice Image. Unfotunately it works only for bitmaps.

**Comment by sambert** [comment]
This is a great concept, but does need some fixing...
Sketch should allow 9-slice to vectors once they are a symbol.
Here is the result of some resizing...

![screen shot 2015-04-19 at 7 10 38 pm](https://cloud.githubusercontent.com/assets/7542647/7219653/cd0fd2a2-e6c7-11e4-804c-fea39634fd31.png)

**Comment by mariuszostrowski** [comment]
Hmm, I don't have that problems. How you do that?

M

2015-04-19 15:42 GMT+02:00 Sameer Bhiwani notifications@github.com:

**Comment by sambert** [comment]
I just opened the file and stretched it vertically :)

**Comment by mariuszostrowski** [comment]
Try to flip vertically if you want arrow in other direction
19 kwi 2015 16:32 "Sameer Bhiwani" notifications@github.com napisał(a):

**Comment by krasnovpro** [comment]
Awesome feature. Thanks a lot for pointing this.

**Comment by dimitrieh** [comment]
@quaritexa plz see this ;) https://twitter.com/dimitrieh/status/745959476348526592
